baseURL: 'https://2023.ubucon.asia/'
languageCode: en-us
title: UbuCon Asia 2023
theme: ubuconasia
Paginate: 5
buildFuture: true
enableRobotsTXT: true
enableGitInfo: true
defaultContentLanguage: en
languages:
  ko:
    languageName: 한국어
    title: 우부콘 아시아 2023
    weight: 2
    params:
      descriptionOnHomepage: >-
        3번째 우부콘 아시아가 인도네시아 수라카르타에 위치한 UNS 의 Aula FKIP (Gedung F)에서 열립니다. 올해 행사는 LibreOffice Conf Asia 와 연합으로 개최됩니다.
      description: 10월 7~8일 | 인도네시아 수라카르타 UNS - Aula FKIP (Gedung F)
      period: 2023년 10월 7~8일 | 인도네시아 수라카르타 UNS - Aula FKIP (Gedung F)
      venueName: UNS - Aula FKIP (Gedung F)
    menu:
      main:
        - identifier: about
          name: 소개
          url: about
          weight: 10
        - identifier: venue-travel-group
          name: 행사장 및 여행정보
          url: venue-and-travel
          weight: 20
        - identifier: venue
          parent: venue-travel-group
          name: 행사장/안전정보
          url: venue-and-travel/venue-and-safety
          weight: 21
        - identifier: entry-and-visa
          parent: venue-travel-group
          name: 입국요건과 비자
          url: venue-and-travel/entry-and-visa
          weight: 22
        - identifier: travel-grants
          parent: venue-travel-group
          name: 여행 경비 지원
          url: venue-and-travel/travel-grants
          weight: 23
        - identifier: accommodations
          parent: venue-travel-group
          name: 근처 숙박시설
          url: venue-and-travel/accommodations
          weight: 24
        - identifier: idtravel
          parent: venue-travel-group
          name: Wonderful Indonesia
          url: https://www.indonesia.travel/
          weight: 26
        - identifier: programs-group
          name: 프로그램
          url: https://events.canonical.com/event/13/abstracts/
          weight: 30
        - identifier: sponsors-group
          name: 후원사/개인후원
          url: sponsors
          weight: 40
        - identifier: become-a-sponsor
          parent: sponsors-group
          name: 후원사 등록 안내
          url: become-a-sponsor
          weight: 41
        - identifier: sponsors
          parent: sponsors-group
          name: 후원사
          url: sponsors
          weight: 42
        - identifier: patrons
          parent: sponsors-group
          name: 개인 후원자
          url: patrons
          weight: 43
        - identifier: news
          name: 소식
          url: news
          weight: 50
        - identifier: wiki
          name: 위키
          url: https://wiki.ubuntu.com/UbuconAsia/2023
          weight: 60
  en:
    languageName: English
    title: UbuCon Asia 2023
    weight: 1
    params:
      descriptionOnHomepage: >-
        The 3rd edition of UbuCon Asia will be held at FKIP UNS ins Surakarta, Indonesia. It will be also a joint event with LibreOffice Conf Asia
      description: October 7th ~ 8th | Aula FKIP (Gedung F), UNS, Surakarta, Indonesia
      period: October 7th ~ 8th, 2023 | Aula FKIP (Gedung F), UNS, Surakarta, Indonesia
      venueName: Aula FKIP (Gedung F), UNS
    menu:
      main:
        - identifier: about
          name: About
          url: about
          weight: 10
        - identifier: venue-travel-group
          name: Venue & Travel
          url: venue-and-travel
          weight: 20
        - identifier: venue
          parent: venue-travel-group
          name: Venue & Safety
          url: venue-and-travel/venue-and-safety
          weight: 21
        - identifier: entry-and-visa
          parent: venue-travel-group
          name: Entry requirements and Visa
          url: venue-and-travel/entry-and-visa
          weight: 22
        - identifier: travel-grants
          parent: venue-travel-group
          name: Travel grants
          url: venue-and-travel/travel-grants
          weight: 23
        - identifier: accommodations
          parent: venue-travel-group
          name: Accomodations
          url: venue-and-travel/accommodations
          weight: 24
        - identifier: idtravel
          parent: venue-travel-group
          name: Wonderful Indonesia
          url: https://www.indonesia.travel/
          weight: 26
        - identifier: programs-group
          name: Programs
          url: https://events.canonical.com/event/13/abstracts/
          weight: 30
        - identifier: sponsors-group
          name: Sponsors/Patrons
          url: sponsors
          weight: 40
        - identifier: become-a-sponsor
          parent: sponsors-group
          name: Become a sponsor
          url: become-a-sponsor
          weight: 41
        - identifier: sponsors
          parent: sponsors-group
          name: Sponsors
          url: sponsors
          weight: 42
        - identifier: patrons
          parent: sponsors-group
          name: Individual patrons
          url: patrons
          weight: 43
        - identifier: news
          name: News
          url: news
          weight: 50
        - identifier: wiki
          name: Wiki
          url: https://wiki.ubuntu.com/UbuconAsia/2023
          weight: 60
  id:
    languageName: Bahasa Indonesia
    title: UbuCon Asia 2023
    weight: 2
    params:
      descriptionOnHomepage: >-
        The 3rd edition of UbuCon Asia will be held at FKIP UNS ins Surakarta, Indonesia. It will be also a joint event with LibreOffice Conf Asia
      description: October 7th ~ 8th | Aula FKIP (Gedung F), UNS, Surakarta, Indonesia
      period: October 7th ~ 8th, 2023 | Aula FKIP (Gedung F), UNS, Surakarta, Indonesia
      venueName: Aula FKIP (Gedung F), UNS
    menu:
      main:
        - identifier: about
          name: Tentang
          url: about
          weight: 10
        - identifier: venue-travel-group
          name: Venue & Travel
          url: venue-and-travel
          weight: 20
        - identifier: venue
          parent: venue-travel-group
          name: Venue & Safety
          url: venue-and-travel/venue-and-safety
          weight: 21
        - identifier: entry-and-visa
          parent: venue-travel-group
          name: Entry requirements and Visa
          url: venue-and-travel/entry-and-visa
          weight: 22
        - identifier: travel-grants
          parent: venue-travel-group
          name: Travel grants
          url: venue-and-travel/travel-grants
          weight: 23
        - identifier: accommodations
          parent: venue-travel-group
          name: Accomodations
          url: venue-and-travel/accommodations
          weight: 24
        - identifier: idtravel
          parent: venue-travel-group
          name: Wonderful Indonesia
          url: https://www.indonesia.travel/
          weight: 26
        - identifier: programs-group
          name: Program
          url: https://events.canonical.com/event/13/abstracts/
          weight: 30
        - identifier: sponsors-group
          name: Sponsor/Patron
          url: sponsors
          weight: 40
        - identifier: become-a-sponsor
          parent: sponsors-group
          name: Become a sponsor
          url: become-a-sponsor
          weight: 41
        - identifier: sponsors
          parent: sponsors-group
          name: Sponsor
          url: sponsors
          weight: 42
        - identifier: patrons
          parent: sponsors-group
          name: Patron Individual
          url: patrons
          weight: 43
        - identifier: news
          name: Berita
          url: news
          weight: 50
        - identifier: wiki
          name: Wiki
          url: https://wiki.ubuntu.com/UbuconAsia/2023
          weight: 60
  ja:
    languageName: 日本語
    title: UbuCon Asia 2023
    weight: 3
    params:
      descriptionOnHomepage: >-
        The 3rd edition of UbuCon Asia will be held at FKIP UNS ins Surakarta, Indonesia. It will be also a joint event with LibreOffice Conf Asia
      description: October 7th ~ 8th | Aula FKIP (Gedung F), UNS, Surakarta, Indonesia
      period: October 7th ~ 8th, 2023 | Aula FKIP (Gedung F), UNS, Surakarta, Indonesia
      venueName: Aula FKIP (Gedung F), UNS
    menu:
      main:
        - identifier: about
          name: Ubucon Asiaとは
          url: about
          weight: 10
        - identifier: venue-travel-group
          name: Venue & Travel
          url: venue-and-travel
          weight: 20
        - identifier: venue
          parent: venue-travel-group
          name: Venue & Safety
          url: venue-and-travel/venue-and-safety
          weight: 21
        - identifier: entry-and-visa
          parent: venue-travel-group
          name: Entry requirements and Visa
          url: venue-and-travel/entry-and-visa
          weight: 22
        - identifier: travel-grants
          parent: venue-travel-group
          name: Travel grants
          url: venue-and-travel/travel-grants
          weight: 23
        - identifier: accommodations
          parent: venue-travel-group
          name: Accomodations
          url: venue-and-travel/accommodations
          weight: 24
        - identifier: idtravel
          parent: venue-travel-group
          name: Wonderful Indonesia
          url: https://www.indonesia.travel/
          weight: 26
        - identifier: programs-group
          name: Programs
          url: https://events.canonical.com/event/13/abstracts/
          weight: 30
        - identifier: sponsors-group
          name: スポンサー/Patrons
          url: sponsors
          weight: 40
        - identifier: become-a-sponsor
          parent: sponsors-group
          name: Become a sponsor
          url: become-a-sponsor
          weight: 41
        - identifier: sponsors
          parent: sponsors-group
          name: スポンサー
          url: sponsors
          weight: 42
        - identifier: patrons
          parent: sponsors-group
          name: Individual patrons
          url: patrons
          weight: 43
        - identifier: news
          name: ニュース
          url: news
          weight: 50
        - identifier: wiki
          name: Wiki
          url: https://wiki.ubuntu.com/UbuconAsia/2023
          weight: 60
  zh-hant-tw:
    languageName: 正體中文(臺灣)
    title: UbuCon Asia 2023
    weight: 2
    params:
      descriptionOnHomepage: >-
        The 3rd edition of UbuCon Asia will be held at FKIP UNS ins Surakarta, Indonesia. It will be also a joint event with LibreOffice Conf Asia
      description: October 7th ~ 8th | Aula FKIP (Gedung F), UNS, Surakarta, Indonesia
      period: October 7th ~ 8th, 2023 | Aula FKIP (Gedung F), UNS, Surakarta, Indonesia
      venueName: Aula FKIP (Gedung F), UNS
    menu:
      main:
        - identifier: about
          name: About
          url: about
          weight: 10
        - identifier: venue-travel-group
          name: Venue & Travel
          url: venue-and-travel
          weight: 20
        - identifier: venue
          parent: venue-travel-group
          name: Venue & Safety
          url: venue-and-travel/venue-and-safety
          weight: 21
        - identifier: entry-and-visa
          parent: venue-travel-group
          name: Entry requirements and Visa
          url: venue-and-travel/entry-and-visa
          weight: 22
        - identifier: travel-grants
          parent: venue-travel-group
          name: Travel grants
          url: venue-and-travel/travel-grants
          weight: 23
        - identifier: accommodations
          parent: venue-travel-group
          name: Accomodations
          url: venue-and-travel/accommodations
          weight: 24
        - identifier: idtravel
          parent: venue-travel-group
          name: Wonderful Indonesia
          url: https://www.indonesia.travel/
          weight: 26
        - identifier: programs-group
          name: Programs
          url: https://events.canonical.com/event/13/abstracts/
          weight: 30
        - identifier: sponsors-group
          name: Sponsors/Patrons
          url: sponsors
          weight: 40
        - identifier: become-a-sponsor
          parent: sponsors-group
          name: Become a sponsor
          url: become-a-sponsor
          weight: 41
        - identifier: sponsors
          parent: sponsors-group
          name: Sponsors
          url: sponsors
          weight: 42
        - identifier: patrons
          parent: sponsors-group
          name: Individual patrons
          url: patrons
          weight: 43
        - identifier: news
          name: News
          url: news
          weight: 50
        - identifier: wiki
          name: Wiki
          url: https://wiki.ubuntu.com/UbuconAsia/2023
          weight: 60
  zh-hans-cn:
    languageName: 简体中文（中国大陆）
    title: UbuCon Asia 2023
    weight: 3
    params:
      descriptionOnHomepage: >-
        首次在韩国举行的 Ubuntu 亚洲峰会。
      description: 11 月 26 至 27 日  | 韩国，首尔市，Nuritkum Square
      period: 2023 年 11 月 26 至 27 日  | 韩国，首尔市，Nuritkum Square
      venueName: Aula FKIP (Gedung F), UNS
    menu:
      main:
        - identifier: about
          name: 关于 Ubucon Asia
          url: about
          weight: 10
        - identifier: venue-travel-group
          name: 场馆指南
          url: venue-and-travel
          weight: 20
        - identifier: venue
          parent: venue-travel-group
          name: 场馆介绍
          url: venue-and-travel/venue-and-safety
          weight: 21
        - identifier: entry-and-visa
          parent: venue-travel-group
          name: Entry requirements and Visa
          url: venue-and-travel/entry-and-visa
          weight: 22
        - identifier: travel-grants
          parent: venue-travel-group
          name: Travel grants
          url: venue-and-travel/travel-grants
          weight: 23
        - identifier: accommodations
          parent: venue-travel-group
          name: Accomodations
          url: venue-and-travel/accommodations
          weight: 24
        - identifier: idtravel
          parent: venue-travel-group
          name: Wonderful Indonesia
          url: https://www.indonesia.travel/
          weight: 26
        - identifier: programs-group
          name: 会议
          url: https://events.canonical.com/event/13/abstracts/
          weight: 30
        - identifier: sponsors-group
          name: 赞助商
          url: sponsors
          weight: 40
        - identifier: sponsors
          parent: sponsors-group
          name: 赞助商
          url: sponsors
          weight: 41
        - identifier: become-a-sponsor
          parent: sponsors-group
          name: Become a sponsor
          url: become-a-sponsor
          weight: 42
        - identifier: patrons
          parent: sponsors-group
          name: 个人赞助者
          url: patrons
          weight: 43
        - identifier: news
          name: 新闻
          url: news
          weight: 44
        - identifier: wiki
          name: Wiki
          url: https://wiki.ubuntu.com/UbuconAsia/2023
          weight: 50
params:
  contact: contact@ubucon.asia
  calendarOrganizer: UbuCon Asia 2023 Organizers
  calendarUidSuffix: 2023.asia.ubucon.org
  facebook: ubuconasia
  twitter: ubuconasia
  github: ubucon-asia
  linkedin: ubucon-asia
  mastodon: https://mastodon.social/@UbuConAsia
  repo: https://github.com/ubucon-asia/2023
  cloudflareAnalyticsToken: 25b3a95f0c9b46ebbe67afb9ea6006b2
  copyright:  >-
    © 2023 UbuCon Asia 2023 Website authors.
    Except where otherwise noted, Website source code licensed under MIT, Contents licensed under CC BY 4.0. 
    Ubuntu and Canonical are registered trademarks of Canonical Ltd.
  email: contact@ubucon.asia
  registerURLs:
    attendee: https://eventyay.com/e/75ac7f83
    callForSpeakers: /cfs
  timetable:
    dateStart: 2023-11-26T10:00:00+09:00
    dateEnd: 2023-11-27T18:00:00+09:00
    timeStart: 2000-01-01T09:00:00+09:00 # Use random date for timeStart param
  eventInfo:
    virtualLocationUrl: https://www.youtube.com/channel/UCdy5ggH4LKgUyr0WIH9DPwQ
    streetAddress: "396, World Cup buk-ro"
    addressLocality: "Mapo-gu"
    postalCode: "03925"
    addressRegion: "Seoul"
    addressCountry: "KR"
outputs:
  home: ["HTML", "RSS", "JSON"]
  section: ["HTML", "RSS", "Calendar", "JSON"]
markup:
  goldmark:
    renderer:
      unsafe: true